### ISSUE TITLE
Push notification without tag?

### ISSUE THREAD

**Issue by RuddyOne** [tiagomtotti/firebaseNet#13]
I maybe missing something but how do I push a notification without a tag? As my app does not require a tag and everyone should receive the notification.

I have left it empty but that does not seem work.

**Comment by RuddyOne** [comment]
I think you can ignore me here. I believe this is not how Firebase works, android expects a topic or id. Think you can close this.

**Comment by tiagomtotti** [comment]
Yep, it does :)

2017-08-21 7:21 GMT-03:00 Alex <notifications@github.com>:
