### ISSUE TITLE
FirebaseNet.Serialization.JsonNetSerializer threw an exception

### ISSUE THREAD

**Issue by pqminh** [tiagomtotti/firebaseNet#18]
I use C# web api target .net 4.5
FirebaseNet 1.0.1
NewtonSoft.json 10.0.2

When I call a new FCM client then "The type initializer for 'FirebaseNet.Serialization.JsonNetSerializer' threw an exception."
Error:
{"Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"}

**Comment by aliexalter** [comment]
You have version 10 firebase required version 9. Remove version 10 and install version 9 of NewtonSoft Json.

**Comment by pqminh** [comment]
@aliexalter tks, I resovled this one.
