### ISSUE TITLE
InvalidRegistration error

### ISSUE THREAD

**Issue by flaviusdemian** [tiagomtotti/firebaseNet#2]
Hello,

I get this error. InvalidRegistration.

Here is the response.

{"multicast_id":7134642900023070392,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"InvalidRegistration"}]}

Do you have any suggestions?

Thank you,

**Comment by tiagomtotti** [comment]
Hi, can you please post the code snippet you're using to send the message, along with the message object?
Thanks

**Comment by flaviusdemian** [comment]
It seems that when I migrated to FCM the server key changed. Now I also get not authorized.
Can you please confirm that the server key is the Web Api key?

![projectsettings](https://cloud.githubusercontent.com/assets/2652146/20246262/fb516a5a-a9bb-11e6-9b7f-c21849f10bbe.png)

**Comment by tiagomtotti** [comment]
On FCM,, you should go to Project Settings -> Cloud Messaging. There you'll find the FCM Token and Server Key.
When I wrote the library a couple of months ago, the Token option wasn't avilable. I'll update the code to support it till tomorrow. For now, you should use the _**Server Key**_ to create the FCM Client.

**Comment by flaviusdemian** [comment]
Ok, Looking forward, Thanks

**Comment by flaviusdemian** [comment]
Do you have any suggested documentation in the meanwhile? We are stuck with this and it is bad. Thanks

**Comment by tiagomtotti** [comment]
Take a look at the integration tests in the project. You should find some
samples there.

Em 13 de nov de 2016 13:28, "Flavius Demian" notifications@github.com
escreveu:

**Comment by flaviusdemian** [comment]
Ok. I will

**Comment by tiagomtotti** [comment]
@slown1 , the invalid registration means that the  device you're specifiying in the "To" section wasn't registered to receive notifications from your project.

You should use the client apis https://firebase.google.com/docs/cloud-messaging/ for Android, IoS, to register the device in your project.

If you want to do a test, you can change the To parameter to "/topics/android". This is a pre-built topic in FCM that will send a message to all android devices,
