### ISSUE TITLE
Receive

### ISSUE THREAD

**Issue by mhsystem** [tiagomtotti/firebaseNet#4]
Hello, how can I receive messages over firebaseNet?

Thank you

**Comment by tiagomtotti** [comment]
Hi! Sorry for the delayed response.
No, you can't. This library purpose is to send push notifications using the Firebase Rest API.

To receive them, you should use the proper Android or IOs SDKs. If you're building a hybrid app, you'll also find methods in the library you're using to handle the push notifications.
